### ISSUE TITLE
Use caffeinate to keep laptop awake whilst running strap.sh?

### ISSUE THREAD

**Issue by sihil** [MikeMcQuaid/strap#124]
I've found that a laptop can go to sleep whilst running `strap.sh` which means that it needs attention (and sometimes a Brewfile will fail if the download is in progress when it falls asleep).

What do you think about running [`caffeinate`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/caffeinate.8.html) in the background to keep it awake (and killing it off at the end)?

This might be a side effect of #123 (i.e. does a working sudo timestamp update keep a laptop awake?). If so feel free to ignore for now until that is resolved.

**Comment by MikeMcQuaid** [comment]
I think this should be up to the up to the user to decide/handle and out of Strap's scope.

**Comment by sihil** [comment]
Out of interest, how do you prevent a machine going to sleep whilst you are provisioning it? I ask because I presume this must be a common problem and so to me it makes sense for strap to solve it - especially since it seems like a trivial fix.

In other circumstances, I would use the keepingyouawake GUI tool, but that's installed by my brewfile so doesn't exist at the time I kick off strap, whilst the caffeinate utility is already baked in to the OS. On my last run I manually ran caffeinate in one terminal whilst running strap in another. This is feasible, but hassle to remember to do.

**Comment by MikeMcQuaid** [comment]
The macOS defaults give enough time for provisioning to complete on my machine.

> I ask because I presume this must be a common problem and so to me it makes sense for strap to solve it - especially since it seems like a trivial fix.

The problem with this reasoning, unfortunately, is that the number of common problems that Strap could solve with trivial fix mean that Strap quickly expands well beyond it's current scope and becomes harder to read, maintain and buggy. Another problem is that I'm not sure it's expected behaviour for scripts like Strap to stop a system from sleeping; particularly if they are on battery.

That said, if you want to submit a really simple PR for it (I'm talking definitely <10 line diff, ideally 2-3 lines) I'll happily review it but no promises that it will get merged.

**Comment by MikeMcQuaid** [comment]
As an aside through my GitHub clickthrough: thanks for your work on The Guardian!
